# Generated by Django 3.2.5 on 2021-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='healthSys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hName', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=200)),
                ('sVersion', models.CharField(max_length=200)),
            ],
        ),
    ]
