# Generated by Django 3.2.5 on 2021-07-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthsys',
            name='sVersion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='healthsys',
            name='system',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
